# Generated by Django 4.2.19 on 2025-02-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('model', models.CharField(max_length=223)),
                ('year', models.PositiveSmallIntegerField()),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('odometer', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='media/car_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.color')),
            ],
        ),
    ]
